### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by parer55** [positive-intentions/chat#18]
Hello,
Thanks for the incredible work.
Would very much appreciate a docker image. Is it something you can see in the future?
Thanks again and have a great one.

**Comment by xoron** [comment]
hey. ive made a start. are you able to help?

i created what i think should work, but i havent worked with docker in a while and i suspect it somthing obvious im doing wrong. it doesnt seem to be working enough for me to test it on the browser.

can you take a looks and let me know what changes i can make to get it ready to merge.

**Comment by parer55** [comment]
Hello! Sorry, I have zero competence on the subject! 🤷‍♂️ 😂 But if I can help in any non technical way, let me know.

**Comment by xoron** [comment]
No probs. I'm sure I'll figure it out another time.

**Comment by parer55** [comment]
Ok thanks anyway. Excited to see the result! 😉
